"""add collected_data model

Revision ID: 1402451b7260
Revises: 36fc89054a2a
Create Date: 2025-12-04 10:19:15.480854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1402451b7260'
down_revision = '36fc89054a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collected_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('original_url', sa.String(length=512), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collected_data')
    # ### end Alembic commands ###
