"""add collected_data model

Revision ID: 4a27a0a7db23
Revises: 1402451b7260
Create Date: 2025-12-04 10:46:51.065943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a27a0a7db23'
down_revision = '1402451b7260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_date', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_deep_collected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('keyword', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_data', schema=None) as batch_op:
        batch_op.drop_column('keyword')
        batch_op.drop_column('is_deep_collected')
        batch_op.drop_column('publish_date')

    # ### end Alembic commands ###
