"""add collected_data model

Revision ID: cdd77c265b82
Revises: 13620c0e3ec3
Create Date: 2025-12-04 11:46:20.653778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd77c265b82'
down_revision = '13620c0e3ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('deep_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('deep_collected_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('publish_date')
        batch_op.drop_column('content')
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('publish_date', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_column('deep_collected_at')
        batch_op.drop_column('deep_content')
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
